/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as UsersRouteImport } from './routes/users'
import { Route as DevicesIndexRouteImport } from './routes/devices/index'
import { Route as DevicesIdRouteImport } from './routes/devices/$id'
import { Route as DevicesRegisterRouteImport } from './routes/devices/register'
import { Route as HotelsIndexRouteImport } from './routes/hotels/index'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as PeopleIdRouteImport } from './routes/people/$id'
import { Route as PeopleRegisterRouteImport } from './routes/people/register'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffRegisterRouteImport } from './routes/staff/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesIndexRoute = DevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesIdRoute = DevicesIdRouteImport.update({
  id: '/devices/$id',
  path: '/devices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRegisterRoute = DevicesRegisterRouteImport.update({
  id: '/devices/register',
  path: '/devices/register',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRegisterRoute = PeopleRegisterRouteImport.update({
  id: '/people/register',
  path: '/people/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRegisterRoute = StaffRegisterRouteImport.update({
  id: '/staff/register',
  path: '/staff/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gestao': typeof GestaoRoute
  '/monitoring': typeof MonitoringRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/devices/$id': typeof DevicesIdRoute
  '/devices/register': typeof DevicesRegisterRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/register': typeof PeopleRegisterRoute
  '/staff/register': typeof StaffRegisterRoute
  '/devices/': typeof DevicesIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gestao': typeof GestaoRoute
  '/monitoring': typeof MonitoringRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/devices/$id': typeof DevicesIdRoute
  '/devices/register': typeof DevicesRegisterRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/register': typeof PeopleRegisterRoute
  '/staff/register': typeof StaffRegisterRoute
  '/devices': typeof DevicesIndexRoute
  '/hotels': typeof HotelsIndexRoute
  '/people': typeof PeopleIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gestao': typeof GestaoRoute
  '/monitoring': typeof MonitoringRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/users': typeof UsersRoute
  '/devices/$id': typeof DevicesIdRoute
  '/devices/register': typeof DevicesRegisterRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/register': typeof PeopleRegisterRoute
  '/staff/register': typeof StaffRegisterRoute
  '/devices/': typeof DevicesIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gestao'
    | '/monitoring'
    | '/profile'
    | '/settings'
    | '/setup'
    | '/users'
    | '/devices/$id'
    | '/devices/register'
    | '/people/$id'
    | '/people/register'
    | '/staff/register'
    | '/devices/'
    | '/hotels/'
    | '/people/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gestao'
    | '/monitoring'
    | '/profile'
    | '/settings'
    | '/setup'
    | '/users'
    | '/devices/$id'
    | '/devices/register'
    | '/people/$id'
    | '/people/register'
    | '/staff/register'
    | '/devices'
    | '/hotels'
    | '/people'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/gestao'
    | '/monitoring'
    | '/profile'
    | '/settings'
    | '/setup'
    | '/users'
    | '/devices/$id'
    | '/devices/register'
    | '/people/$id'
    | '/people/register'
    | '/staff/register'
    | '/devices/'
    | '/hotels/'
    | '/people/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GestaoRoute: typeof GestaoRoute
  MonitoringRoute: typeof MonitoringRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  UsersRoute: typeof UsersRoute
  DevicesIdRoute: typeof DevicesIdRoute
  DevicesRegisterRoute: typeof DevicesRegisterRoute
  PeopleIdRoute: typeof PeopleIdRoute
  PeopleRegisterRoute: typeof PeopleRegisterRoute
  StaffRegisterRoute: typeof StaffRegisterRoute
  DevicesIndexRoute: typeof DevicesIndexRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/': {
      id: '/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof DevicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$id': {
      id: '/devices/$id'
      path: '/devices/$id'
      fullPath: '/devices/$id'
      preLoaderRoute: typeof DevicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/register': {
      id: '/devices/register'
      path: '/devices/register'
      fullPath: '/devices/register'
      preLoaderRoute: typeof DevicesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/register': {
      id: '/people/register'
      path: '/people/register'
      fullPath: '/people/register'
      preLoaderRoute: typeof PeopleRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/register': {
      id: '/staff/register'
      path: '/staff/register'
      fullPath: '/staff/register'
      preLoaderRoute: typeof StaffRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GestaoRoute: GestaoRoute,
  MonitoringRoute: MonitoringRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  UsersRoute: UsersRoute,
  DevicesIdRoute: DevicesIdRoute,
  DevicesRegisterRoute: DevicesRegisterRoute,
  PeopleIdRoute: PeopleIdRoute,
  PeopleRegisterRoute: PeopleRegisterRoute,
  StaffRegisterRoute: StaffRegisterRoute,
  DevicesIndexRoute: DevicesIndexRoute,
  HotelsIndexRoute: HotelsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
